### ISSUE TITLE
`node build.js` not working

### ISSUE THREAD

**Issue by jpadams** [dagger/examples#15]

**Comment by kpenfound** [comment]
What issues are you seeing? Works fine for me on node 16.17

**Comment by d3rp3tt3** [comment]
I think it's missing the final parentheses, like this issue I opened on the Dagger docs: https://github.com/dagger/dagger/issues/4451.

**Comment by jpadams** [comment]
> I think it's missing the final parentheses, like this issue I opened on the Dagger docs: [dagger/dagger#4451](https://github.com/dagger/dagger/issues/4451).

@d3rp3tt3 no, that final `()` would be in a Common JS style. This file is in the ES Module style and either needs an `.mjs` file extension or like this project has, a `  "type": "module",` line in the `package.json`.

The issue was me forgetting to run `npm install` or `yarn install` to actually install all of the required dependencies in the `package.json` before running `node build.js`. So it's all 👍
