### ISSUE TITLE
Add PHP and Rust code examples for creating custom GraphQL clients

### ISSUE THREAD

**Issue by d3rp3tt3** [dagger/examples#17]
### What is the issue?

The Dagger docs include examples of creating a GraphQL client to work with Dagger in languages that aren't in one of the official SDKs. 

It would be nice to have these examples in this Examples repo. 

Dagger doc with inline examples: [Build a Custom API Client](https://docs.dagger.io/api/254103/build-custom-client)

**Comment by jpadams** [comment]
Thanks, @d3rp3tt3, good suggestion.

**Comment by jpadams** [comment]
@d3rp3tt3 We've moved all of the examples to https://github.com/dagger/dagger/tree/main/examples. Could you please reopen this issue in https://github.com/dagger/dagger 🙏 Thank you!

We will archive this repo.
