### ISSUE TITLE
Dagger installation options: Drop the shell script

### ISSUE THREAD

**Issue by xinity** [dagger/examples#21]
I think the executable script used with curl isn't really deserving that project as there were many fuds back in the days when Docker was installable using the same mechanism.

Having, brew, binary and source method is by far enough IMHO 

putting also the fact that this method (shell script) will definitely raise at some point, security concerns

**Comment by samalba** [comment]
Curious to know what other people think regarding the trade-off between convenience and security. I am fine to deprecate if enough think the binaries + homebrew are enough.

**Comment by samalba** [comment]
Closing this here, we'll track it from https://github.com/dagger/dagger/issues/702 instead (this is about `dagger/dagger`, not examples).
