### ISSUE TITLE
Dagger Installation procedure: rework the binary move using sudo

### ISSUE THREAD

**Issue by xinity** [dagger/examples#22]
there's no need to suggest moving the binary to /usr/local/bin as there are safer ways to make dagger binary available in the user path.

for example we can simply do either: 
` export PATH=$PATH:$HOME/bin` 
    or 
    add into the .bashrc file :
```
    # testing if dagger binary is present and updating user PATH  
    if [ -f ${HOME}/bin/dagger ]; then
	export PATH=$PATH:$HOME/bin
    fi
```

users who would want to test out dagger doesn't necessarily have sudo privileges :(

**Comment by gerhard** [comment]
We now capture this on the first page on the updated Dagger 0.2 (a.k.a. Europa) docs for Linux:
https://docs.dagger.io/
![image](https://user-images.githubusercontent.com/3342/157734557-e129dc7b-8ba9-4c59-bd70-1b43a8f45818.png)

We assume that Linux users are familiar with the terminal and don't need help configuring `PATH` or anything else dagger binary-related.
