### ISSUE TITLE
✨ Add example for Elixir SDK

### ISSUE THREAD

**Issue by wingyplus** [dagger/examples#31]
### What are you trying to do?

I working on Elixir SDK documentation (https://github.com/dagger/dagger/pull/5530) and see that it needs to add examples into this repository. So I want to create this issue for tracking the progress.

* [ ] Core concepts section
  * [ ] Mounting source files to a container.
  * [ ] Multi-stage build (https://github.com/dagger/examples/pull/32)
  * [ ] Multi-platform build
  * [ ] Cache mounts
  * [ ] Concurrency
  * [ ] Container publishing
  * [ ] Secrets
  * [ ] Services
  * [ ] Testing your pipelines
* [ ] By language section
  * [ ] phoenix application build
  
I believe that the list above is enough for the first start. Feel free to comment for what am I missing.

**Comment by jpadams** [comment]
@wingyplus We've moved all of the examples to https://github.com/dagger/dagger/tree/main/examples. Could you please reopen this issue in https://github.com/dagger/dagger 🙏 Thank you!

We will archive this repo.
