### ISSUE TITLE
`dagger up` results in error for todoapp example

### ISSUE THREAD

**Issue by benjaminxscott** [dagger/examples#35]
## Repro
- Clone this repo
- `cd todoapp`
- `dagger up`
- Process emits error that "jq is not installed", process exits

Output: https://gist.github.com/benjaminxscott/c59218cba81a577364d56b44829f0011

Running `dagger up` a second time resulted in successful execution and environment deployment

Looks like there was a transient error in contacting the image registry during the first execution, which wasn't present in the second execution (possibly network issue on my side)

## Environment
Linux container on ChromeOS Version 91.0.4472.114 (Official Build) (64-bit)

> dagger version

dagger 0.1.0-alpha.20 (8462963) linux/amd64

> uname -a

Linux penguin 5.4.99-12983-g8b7876ab9f5e #1 SMP PREEMPT Sun Feb 21 11:49:12 PST 2021 x86_64 GNU/Linux

> cat /etc/issue

Debian GNU/Linux 10

**Comment by grouville** [comment]
Thanks @benjaminxscott, we were moving the examples a lot, with some breaking changes. However, it could indeed show a race condition. Did it happen again ? I'm not able to reproduce it locally though :'(

**Comment by benjaminxscott** [comment]
I think this was due to a network connectivity issue that caused a race condition like you noted 
(e.g. "we started building the image, but then couldn't get to the internet to install jq")
