### ISSUE TITLE
Rename to dagger-examples

### ISSUE THREAD

**Issue by gerhard** [dagger/examples#53]
Having forked this, the repository name doesn't tell me that these are dagger examples:
<img width="269" alt="image" src="https://user-images.githubusercontent.com/3342/154376194-a0d6601b-2a84-4adf-984e-aeeb505db3af.png">

While the fork info helps in the GitHub web UI, it doesn't locally:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/3342/154376341-5e05ca2a-eb5c-441b-8782-9b723ef1c45b.png">

I think that we should rename the repository from:

```diff
- dagger/examples
+ dagger/dagger-examples
```

I know that this will have a knock-on effect on a few tests and docs (possibly other things), but I would prefer that we did this before launch.

WDYT?

**Comment by samalba** [comment]
+1 for renaming it, I did not think about the fork naming issue, but it makes sense.

**Comment by gerhard** [comment]
Ok, sounds great, I will circle back when I'm done with the higher priority PRs.
If anyone beats me to it and solves this before, I will not be upset 😉

**Comment by gerhard** [comment]
This is no longer in scope since https://github.com/dagger/examples/issues/59, closing.
